version: "3"
services:
  server:
    image: hacking-higher-ed:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    restart: on-failure
